### ISSUE TITLE
mish panic when typing 'r'

### ISSUE THREAD

**Issue by nicks** [windmilleng/mish#5]
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/windmilleng/mish/mish.(*scrollCanvas).RenderAt(0xc4201aac00, 0x0, 0x20, 0x9)
	/Users/nick/go/src/github.com/windmilleng/mish/mish/canvas.go:69 +0x1c6
github.com/windmilleng/mish/mish.(*Render).renderShmill(0xc4205bdc18, 0xc4202d8000, 0x0, 0x0, 0x0)
	/Users/nick/go/src/github.com/windmilleng/mish/mish/view.go:164 +0x758
github.com/windmilleng/mish/mish.(*Render).Render(0xc4205bdc18, 0xc4202d8000, 0xc4205ba3b0, 0x1, 0x1)
	/Users/nick/go/src/github.com/windmilleng/mish/mish/view.go:39 +0xc1
github.com/windmilleng/mish/mish.(*View).Render(0x1a63398, 0xc4202d8000, 0xc4202d2270, 0x0, 0x0)
	/Users/nick/go/src/github.com/windmilleng/mish/mish/view.go:20 +0x3d
github.com/windmilleng/mish/mish.(*Shell).Run(0xc4202d6000, 0x0, 0x0)
	/Users/nick/go/src/github.com/windmilleng/mish/mish/shell.go:164 +0x3fd
main.main()
	/Users/nick/go/src/github.com/windmilleng/mish/cmd/mish/main.go:19 +0x7e

**Comment by chuckha** [comment]
This happens to me when mish is running already and I push 'r'.

**Comment by dexhorthy** [comment]
+1 I get this as well when pressing `r` in the middle of running an `sh()` command
```
panic: send on closed channel                                    6.2s elapsed
╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌
github.com/windmilleng/windmill/mish/shmill.(*ex).Sh.func1(0xc4201e5c40, 0xc4203b0010, 0xc42029c120, 0xc4203b6000)                                          
go vet ./Users/dan/go/src/github.com/windmilleng/windmill/mish/shmill/shmill.go:176 +0x88
<snip>
```
Using this release 0.1.1 https://github.com/windmilleng/mish/releases/tag/v0.1.1

My `notes.mill`: 

```python
sh("make build")
sh("ginkgo -p -noColor integration")

def wf_mockgen():
    sh("make mockgen")
```
